### ISSUE TITLE
UIKit refreshing issue

### ISSUE THREAD

**Issue by nonameplum** [chriseidhof/reducers-examples#1]
Hey, I really love your article about reducers http://chris.eidhof.nl/post/reducers/ . One thing that for me is a little bit confusing is how to deal with UIKit using this concept. Because `didSet` method will be called on every State change regardless which property has changed. I check your playground with currency conversion, and didSet is called a lot of times and growing fast which means in more complicated UI will provide refreshing all of the UI components connected to that state. I know that this concept is somehow based on this, but because of UIKit it would be great to refresh only those things that really changed to avoid possible blinking, flashing and other unwanted behaviors. Did you think about this problem and how could be addressed in the UIKit world?

**Comment by FaiChou** [comment]
![bug-report](https://user-images.githubusercontent.com/18500846/27992391-5ee4cf92-64c6-11e7-8c08-c289d4abb512.png)

Hi, I just confused about your playground. When I first launch the `currency conversion - reducer`, I notice that when I tapped the `reload` button, the `didSet` execute twice, the first is `State(inputAmount: nil, rate: nil)`, the other is `State(inputAmount: nil, rate: Optional(1.1412))`.

**Comment by FaiChou** [comment]
![currency conversation reducer](http://o7bkcj7d7.bkt.clouddn.com/markdown/1499590633891.png)

Hi, I just confused about your playground. When I first launch the currency conversion - reducer, I notice that when I tapped the reload button, the didSet execute twice, the first is State(inputAmount: nil, rate: nil), the other is State(inputAmount: nil, rate: Optional(1.1412)).
What confused me is why the `state` change on the first time? It is a struct, and what changes on the first time?
Thanks

@nonameplum 
@chriseidhof

**Comment by FaiChou** [comment]
Oh, I see.

In struct function, you just called mutating function then the struct is changed.

**Comment by chriseidhof** [comment]
Exactly!
